ALTER TABLE application.criteria
   DROP CONSTRAINT FK_CRITERIA_ON_SOURCE,
   DROP CONSTRAINT FK_CRITERIA_ON_ENTRY_TYPE,
   DROP CONSTRAINT FK_CRITERIA_ON_CREATED_BY,
   DROP CONSTRAINT FK_CRITERIA_ON_UPDATED_BY,
   ADD CONSTRAINT FK_CRITERIA_ON_SOURCE FOREIGN KEY (source_id) REFERENCES application.source (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_CRITERIA_ON_ENTRY_TYPE FOREIGN KEY (entry_type_id) REFERENCES application.entry_type (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_CRITERIA_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_CRITERIA_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE application.criteria_has_keyword
   DROP CONSTRAINT fk_crihaskey_on_criteria_entity,
   DROP CONSTRAINT fk_crihaskey_on_keyword_entity,
   ADD CONSTRAINT fk_crihaskey_on_criteria_entity FOREIGN KEY (criteria_id) REFERENCES application.criteria (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT fk_crihaskey_on_keyword_entity FOREIGN KEY (keyword_id) REFERENCES application.keyword (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE application.idea
   DROP CONSTRAINT FK_IDEA_ON_SOURCE,
   DROP CONSTRAINT FK_IDEA_ON_ENTRY_TYPE,
   DROP CONSTRAINT FK_IDEA_ON_CREATED_BY,
   DROP CONSTRAINT FK_IDEA_ON_UPDATED_BY,
   ADD CONSTRAINT FK_IDEA_ON_SOURCE FOREIGN KEY (source_id) REFERENCES application.source (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_IDEA_ON_ENTRY_TYPE FOREIGN KEY (entry_type_id) REFERENCES application.entry_type (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_IDEA_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_IDEA_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE application.idea_and_criteria
   DROP CONSTRAINT FK_IDEA_AND_CRITERIA_ON_IDEA,
   DROP CONSTRAINT FK_IDEA_AND_CRITERIA_ON_CRITERIA,
   DROP CONSTRAINT FK_IDEA_AND_CRITERIA_ON_SOURCE,
   DROP CONSTRAINT FK_IDEA_AND_CRITERIA_ON_CREATED_BY,
   DROP CONSTRAINT FK_IDEA_AND_CRITERIA_ON_UPDATED_BY,
   ADD CONSTRAINT FK_IDEA_AND_CRITERIA_ON_IDEA FOREIGN KEY (idea_id) REFERENCES application.idea (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_IDEA_AND_CRITERIA_ON_CRITERIA FOREIGN KEY (criteria_id) REFERENCES application.criteria (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_IDEA_AND_CRITERIA_ON_SOURCE FOREIGN KEY (source_id) REFERENCES application.source (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_IDEA_AND_CRITERIA_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_IDEA_AND_CRITERIA_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE application.idea_has_keyword
   DROP CONSTRAINT fk_idehaskey_on_idea_entity,
   DROP CONSTRAINT fk_idehaskey_on_keyword_entity,
    ADD CONSTRAINT fk_idehaskey_on_idea_entity FOREIGN KEY (idea_id) REFERENCES application.idea (id) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT fk_idehaskey_on_keyword_entity FOREIGN KEY (keyword_id) REFERENCES application.keyword (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE application.vcw
   DROP CONSTRAINT FK_VCW_ON_BUSINESS_MODEL_CANVAS,
   DROP CONSTRAINT FK_VCW_ON_CREATED_BY,
   DROP CONSTRAINT FK_VCW_ON_UPDATED_BY,
   ADD CONSTRAINT FK_VCW_ON_BUSINESS_MODEL_CANVAS FOREIGN KEY (business_model_canvas_id) REFERENCES application.business_model_canvas (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_VCW_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_VCW_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE application.kpi
   DROP CONSTRAINT FK_KPI_ON_VCW,
   DROP CONSTRAINT FK_KPI_ON_CREATED_BY,
   DROP CONSTRAINT FK_KPI_ON_UPDATED_BY,
   ADD CONSTRAINT FK_KPI_ON_VCW FOREIGN KEY (vcw_id) REFERENCES application.vcw (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_KPI_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_KPI_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE application.project
   DROP CONSTRAINT FK_PROJECT_ON_THUMBNAIL,
   DROP CONSTRAINT FK_PROJECT_ON_CREATED_BY,
   DROP CONSTRAINT FK_PROJECT_ON_UPDATED_BY,
   ADD CONSTRAINT FK_PROJECT_ON_THUMBNAIL FOREIGN KEY (thumbnail) REFERENCES application.file (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_PROJECT_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_PROJECT_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE application.project_has_keyword
   DROP CONSTRAINT fk_prohaskey_on_project_entity,
   DROP CONSTRAINT fk_prohaskey_on_keyword_entity,
   ADD CONSTRAINT fk_prohaskey_on_project_entity FOREIGN KEY (project_id) REFERENCES application.project (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT fk_prohaskey_on_keyword_entity FOREIGN KEY (keyword_id) REFERENCES application.keyword (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE application.project_has_user_role
   DROP CONSTRAINT FK_PROJECT_HAS_USER_ROLE_ON_PROJECT,
   DROP CONSTRAINT FK_PROJECT_HAS_USER_ROLE_ON_ROLE,
   DROP CONSTRAINT FK_PROJECT_HAS_USER_ROLE_ON_CREATED_BY,
   DROP CONSTRAINT FK_PROJECT_HAS_USER_ROLE_ON_UPDATED_BY,
   DROP CONSTRAINT FK_PROJECT_HAS_USER_ROLE_ON_USER_INUM,
   ADD CONSTRAINT FK_PROJECT_HAS_USER_ROLE_ON_PROJECT FOREIGN KEY (project_id) REFERENCES application.project (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_PROJECT_HAS_USER_ROLE_ON_ROLE FOREIGN KEY (role_id) REFERENCES application.role (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_PROJECT_HAS_USER_ROLE_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_PROJECT_HAS_USER_ROLE_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_PROJECT_HAS_USER_ROLE_ON_USER_INUM FOREIGN KEY (user_inum) REFERENCES identity.user_entity (id) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE application.project_has_vcw
   DROP CONSTRAINT FK_PROJECT_HAS_VCW_ON_PROJECT,
   DROP CONSTRAINT FK_PROJECT_HAS_VCW_ON_VCW,
   ADD CONSTRAINT FK_PROJECT_HAS_VCW_ON_PROJECT FOREIGN KEY (project_id) REFERENCES application.project (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_PROJECT_HAS_VCW_ON_VCW FOREIGN KEY (vcw_id) REFERENCES application.vcw (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE application.attachment
   DROP CONSTRAINT FK_ATTACHMENT_ON_FILE,
   DROP CONSTRAINT FK_ATTACHMENT_ON_VCW,
   ADD CONSTRAINT FK_ATTACHMENT_ON_FILE FOREIGN KEY (file_id) REFERENCES application.file (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_ATTACHMENT_ON_VCW FOREIGN KEY (vcw_id) REFERENCES application.vcw (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE application.diagnostic
   DROP CONSTRAINT FK_DIAGNOSTIC_ON_VCW,
   DROP CONSTRAINT FK_DIAGNOSTIC_ON_CREATED_BY,
   DROP CONSTRAINT FK_DIAGNOSTIC_ON_UPDATED_BY,
   ADD CONSTRAINT FK_DIAGNOSTIC_ON_VCW FOREIGN KEY (vcw_id) REFERENCES application.vcw (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_DIAGNOSTIC_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_DIAGNOSTIC_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE application.vcw_has_criteria
   DROP CONSTRAINT FK_VCW_HAS_CRITERIA_ON_VCW,
   DROP CONSTRAINT FK_VCW_HAS_CRITERIA_ON_CRITERIA,
   ADD CONSTRAINT FK_VCW_HAS_CRITERIA_ON_VCW FOREIGN KEY (vcw_id) REFERENCES application.vcw (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_VCW_HAS_CRITERIA_ON_CRITERIA FOREIGN KEY (criteria_id) REFERENCES application.criteria (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE application.vcw_has_idea
   DROP CONSTRAINT FK_VCW_HAS_IDEA_ON_VCW,
   DROP CONSTRAINT FK_VCW_HAS_IDEA_ON_IDEA,
   ADD CONSTRAINT FK_VCW_HAS_IDEA_ON_VCW FOREIGN KEY (vcw_id) REFERENCES application.vcw (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_VCW_HAS_IDEA_ON_IDEA FOREIGN KEY (idea_id) REFERENCES application.idea (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE application.vcw_has_phase
   DROP CONSTRAINT FK_VCW_HAS_PHASE_ON_VCW,
   DROP CONSTRAINT FK_VCW_HAS_PHASE_ON_PHASE,
   ADD CONSTRAINT FK_VCW_HAS_PHASE_ON_VCW FOREIGN KEY (vcw_id) REFERENCES application.vcw (id) ON DELETE CASCADE ON UPDATE CASCADE,
   ADD CONSTRAINT FK_VCW_HAS_PHASE_ON_PHASE FOREIGN KEY (phase_id) REFERENCES application.phase (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE application.file
   DROP CONSTRAINT FK_FILE_ON_CREATED_BY,
   DROP CONSTRAINT FK_FILE_ON_UPDATED_BY,
   ADD CONSTRAINT FK_FILE_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_FILE_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE application.entry_type
   DROP CONSTRAINT FK_ENTRY_TYPE_ON_CREATED_BY,
   DROP CONSTRAINT FK_ENTRY_TYPE_ON_UPDATED_BY,
   ADD CONSTRAINT FK_ENTRY_TYPE_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_ENTRY_TYPE_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE application.business_model_canvas
   DROP CONSTRAINT FK_BUSINESS_MODEL_CANVAS_ON_CREATED_BY,
   DROP CONSTRAINT FK_BUSINESS_MODEL_CANVAS_ON_UPDATED_BY,
   ADD CONSTRAINT FK_BUSINESS_MODEL_CANVAS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_BUSINESS_MODEL_CANVAS_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE application.source
   DROP CONSTRAINT FK_SOURCE_ON_CREATED_BY,
   DROP CONSTRAINT FK_SOURCE_ON_UPDATED_BY,
   ADD CONSTRAINT FK_SOURCE_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
   ADD CONSTRAINT FK_SOURCE_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE application.keyword
    DROP CONSTRAINT FK_KEYWORD_ON_CREATED_BY,
    DROP CONSTRAINT FK_KEYWORD_ON_UPDATED_BY,
    ADD CONSTRAINT FK_KEYWORD_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE,
    ADD CONSTRAINT FK_KEYWORD_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES identity.user_entity (id) ON DELETE SET NULL ON UPDATE CASCADE;