version: '3'

services:
  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION}
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./.docker/database:/var/lib/postgresql/data
      - ./packages/database:/docker-entrypoint-initdb.d

  identity:
    container_name: identity
    env_file: .env
    build:
      context: ./packages/identity
      dockerfile: ../../infra/Dockerfile.identity
      args:
        KC_VERSION: ${KC_VERSION}
    environment:
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_PORT: ${KC_DB_URL_PORT}
      KC_DB_URL_DATABASE: ${DB_DATABASE}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - 8080:8080
    depends_on:
      - database