apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "app.name" . }}-role
rules:
  - apiGroups: [""]
    verbs: ["get", "list", "watch"]
    resources: ["configmaps", "services", "endpoints", "secrets"]