apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "app.name" . }}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "app.name" . }}-service-account
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "app.name" . }}-role
  apiGroup: rbac.authorization.k8s.io