{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}-secrets
type: Opaque
data:
  {{- range $key, $val := .Values.secret.variables.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{- end }}