{{- if .Values.roleBinding.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.name }}
{{- with .Values.role.rules }}
subjects:
{{- toYaml . | nindent 4 }}
{{- end }}
roleRef:
  kind: Role
  name: {{ .Values.role.name }}
  apiGroup: {{ .Values.roleBinding.roleRef.apiGroup }}
{{- end }}