# Default values for request4EO.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ---------------------------------------
# Global variables
# ---------------------------------------
nameOverride: ""
fullnameOverride: ""
restartPolicy: Always

# ---------------------------------------------
# Variable used in hpa template and deployment
# ---------------------------------------------
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# ---------------------------------------
# Variable used in Secret template
# ---------------------------------------
secret:
  enabled: true
  name: vcw-identity-secrets
  variables:
    normals:
      KC_HOSTNAME: 0.0.0.0
      KC_DB_URL_HOST: null
      KC_DB_URL_PORT: null
      KC_DB_URL_DATABASE: null
      KC_DB_SCHEMA: null
      KEYCLOAK_ADMIN: null
      KC_PROXY: "edge"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: true
    secrets:
      KC_DB_USERNAME: null
      KC_DB_PASSWORD: null
      KEYCLOAK_ADMIN_PASSWORD: null

# ---------------------------------------
# Variable used in ConfigMap template
# ---------------------------------------
configmap:
  enabled: false
  name: vcw-identity-configmap

# ---------------------------------------
# Variable used in Deployment template
# ---------------------------------------
deployment:
  replicaCount: 1
  # Additional Pod annotations
  podAnnotations: {}
  # Image pull secrets for the Pod
  imagePullSecrets:
    - name: vcw-identity-registrypullsecret
  # SecurityContext for the entire Pod. Every container running in the Pod will inherit this SecurityContext. This might be relevant when other components of the environment inject additional containers into running Pods (service meshes are the most prominent example for this)
  podSecurityContext:
    # fsGroup: 2000
  # SecurityContext for the nextocean container
  securityContext:
    # runAsUser: 1000
    # runAsNonRoot: true
  image:
    repository: harbor.services4eo.com/vcw/vcw-identity
    pullPolicy: Always
  ## Overrides the default args for the nextocean container
  args: []
  # Additional environment variables for nextocean mapped from Secret or ConfigMap
  extraEnvFrom: ""
  # Define which port will be used in the containers
  containerPort: 8080
  # Startup probe configuration
  startupProbe: { }
  # Liveness probe configuration
  livenessProbe: {}
  # Readiness probe configuration
  readinessProbe: {} #| CHECK LATE
    #  httpGet:
    #    path: /req/actuator/health/readiness
    #    port: 8080
    #  initialDelaySeconds: 10
    #  periodSeconds: 5
    #  timeoutSeconds: 1
    #  failureThreshold: 3
  # Pod resource requests and limits
  resources: {}
  # Node labels for Pod assignment
  nodeSelector: {}
  # Pod affinity
  affinity: {}
  # Node taints to tolerate
  tolerations: []

# ---------------------------------------
# Variable group used in ingress template
# ---------------------------------------
ingress:
  enabled: true
  className: ""
  domain: 127-0-0-1.nip.io
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
  hosts:
    - host: vcw-identity
      paths:
        - path: /
          pathType: Prefix
         
  tls: {}

# ---------------------------------------
# Variable group used in ingress template
# ---------------------------------------
service:
  type: ClusterIP
  port: 8080

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "configmap-reader"

# ---------------------------------------
# Variable group used in role template
# ---------------------------------------
role:
  enabled: false
  name: role-configmap-reader
  rules:
    - apiGroups: [""]
      verbs: ["get", "list", "watch"]
      resources: ["configmaps", "pods", "services", "endpoints", "secrets"]

# ---------------------------------------------
# Variable group used in role binding template
# ---------------------------------------------
roleBinding:
  enabled: false
  name: rolebinding-configmap-reader
  subjects:
    - kind: ServiceAccount
      name: configmap-reader
      apiGroup: ""
  roleRef:
    apiGroup: rbac.authorization.k8s.io
